
[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "screen-256color"

[font]
size = 16.0

[font.bold]
family = "Hack Nerd Font"
style = "bold"

[font.italic]
family = "Hack Nerd Font"
style = "italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002&"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002%"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\""
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002x"
key = "X"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"

[mouse]
hide_when_typing = true

[scrolling]
history = 1000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[terminal.shell]
args = ["-l", "-c", "tmux attach || tmux new -s HelloWorld"]
program = "/bin/zsh"

[window]
decorations = "buttonless"
dynamic_padding = false
dynamic_title = true
opacity = 0.9
option_as_alt = "Both"
title = "Alacritty"

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x = 2
y = 2

[window.position]
x = 220
y = 140

[general]
live_config_reload = true
import = ["/Users/alexcao/.config/alacritty/themes/themes/tokyo-night.toml"]

[terminal]
